### ISSUE TITLE
can't find the STITCHED file

### ISSUE THREAD

**Issue by wisRen** [Marmzy/ROSE#20]
<img width="2018" alt="image" src="https://github.com/Marmzy/ROSE/assets/96978852/a1c29220-c3dd-497b-af6c-dc3efdd3bcee">
The file has been generated in output/gff directory: HG18_MM1S_MED1_12.5kb_stitched_TSS_distal.gff3
However, "STITCHED=$(find ${PWD}/${VALUE_O}/gff -name "$(basename ${VALUE_I%.*}*_distal.gff3)" | head -n 1)" this file cannot be find using this code.
I added  "echo $STITCHED", "echo $ORIGINAL" in ROSE.sh file, which printed $ORIGINAL correctly, while $STITCHED was not found.

**Comment by Marmzy** [comment]
I thought the issue might be due to differing paths, or paths containing special characters such as spaces or hyphens, but that doesn't seem to be the case. To be completely honest, I don't really know why it would be able to find ORIGINAL, but not STITCHED.

In any case, the "find" method seems to be the issue and frankly is probably not a reliable way to get the correct file. I'm pretty sure I can simply convert ROSE.sh to python code, which can give me better control over variable names as I can pass variables between scripts. I think converting the bash code to python might solve the issue .

**Comment by Marmzy** [comment]
Rewrite `ROSE.sh` to python code (`ROSE.py`). This eliminates the need to search for generated files in the system and thus should resolve the issue.
